### ISSUE TITLE
Fix illegible molecule representation

### ISSUE THREAD

**Issue by RainierBarrett** [hgandhi2411/CG-Mapper#11]
The SMILES string "CC1=CC23CN4CC2C4C(CC1)N3" produces bizarre behavior that makes the mapping selection unreadable. We should track down the cause of this display issue and fix it, if possible.
![image (2)](https://user-images.githubusercontent.com/13456066/67704713-01a77480-f98c-11e9-8a72-b5153d87e4ee.png)

**Comment by whitead** [comment]
Can you verify on another smiles viewer that this is valid smiles?

**Comment by hgandhi2411** [comment]
This is from the pubchem drawer
![image](https://user-images.githubusercontent.com/22055417/74772559-3ce0f280-525e-11ea-8b45-4f19c7b24749.png)

**Comment by RainierBarrett** [comment]
This is what it looks like on cheminfo.org:

![image](https://user-images.githubusercontent.com/13456066/74772573-44a09700-525e-11ea-9602-5c94092f250d.png)

**Comment by whitead** [comment]
Probably this is a won't fix. The library we use barfs on non-planar molecules. Happy to hear ideas though.
